image:
  file: .gitpod.Dockerfile
tasks:
  - init: mvn install -DskipTests=false

vscode:
  extensions:
    - redhat.fabric8-analytics
    - redhat.java
    - vscjava.vscode-java-debug
    - sonarsource.sonarlint-vscode
    - github.vscode-pull-request-github
    - pivotal.vscode-spring-boot
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-java-test
    - vscjava.vscode-java-pack
