apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.stage }}-{{ .Values.pv.configpvc }}
spec:
  storageClassName: {{ .Values.stage }}-mfconfigstorage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.pv.configstoragesize }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.stage }}-nfsstorage
spec:
  storageClassName: {{ .Values.stage }}-mfconfigstorage
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: {{ .Values.pv.configstoragesize }}
  hostPath:
    path: {{ .Values.pv.mntpath }}{{ .Values.stage }}{{ .Values.pv.configstorage }}
    type: DirectoryOrCreate 


