server.port: 7001
logging:
  level:
    root: INFO
    de.hf.myfinance: DEBUG

spring.data.mongodb:
  host: 192.168.100.73
  port: 30023
  database: instrument-db
  authentication-database: admin
  username: root
  password: vulkan
  auto-index-creation: true

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: de.hf.myfinance
  pathsToMatch: /**

spring:
  cloud:
    function:
      definition: validateInstrumentProcessor;saveInstrumentProcessor;saveInstrumentTreeProcessor

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.validateInstrumentProcessor-in-0:
    destination: validateInstrumentRequest
    group: validateInstrumentsGroup
  bindings.instrumentApproved-out-0:
    destination: instrumentApproved
    producer:
      required-groups: instrumentApprovedAuditGroup
  bindings.saveInstrumentProcessor-in-0:
    destination: instrumentApproved
    group: saveInstrumentGroup
  bindings.saveInstrumentTreeProcessor-in-0:
    destination: instrumentApproved
    group: saveinstrumentTreeGroup
  bindings.valueProcessor-in-0:
    destination: valueCurveCalculated
    group: instrumentValueGroup
  bindings.validateInstrumentRequest-out-0:
    destination: validateInstrumentRequest
    producer:
      required-groups: validateInstrumentauditGroup

spring.cloud.stream.rabbit.bindings:
  validateInstrumentProcessor-in-0:
    autoBindDlq: true
    republishToDlq: true
  saveInstrumentProcessor-in-0:
    autoBindDlq: true
    republishToDlq: true
  saveInstrumentTreeProcessor-in-0:
    autoBindDlq: true
    republishToDlq: true


spring.rabbitmq:
  host: localhost
  port: 30021
  username: user
  password: vulkan

api:

  common:
    version: 1.0.0
    title: MF instruments API
    description: REST API to create update and read instruments.

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information


---

spring.config.activate.on-profile: local
spring.data.mongodb:
  host: localhost
  port: 30023
  authentication-database: admin
  database: instrument-db
  username: root
  password: vulkan
  auto-index-creation: true