server.port: 7001
logging:
  level:
    root: INFO
    de.hf.myfinance: DEBUG

spring.data.mongodb:
  host: 192.168.100.73
  port: 30029
  database: instrument-db
  authentication-database: admin
  username: root
  password: vulkan

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: de.hf.myfinance
  pathsToMatch: /**

api:

  common:
    version: 1.0.0
    title: MF instruments API
    description: REST API to create update and read instruments.

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information

---
spring.config.activate.on-profile: k8n

spring.data.mongodb:
  host: mfmongo
  port: 30029
  database: instrument-db