/** ----------------------------------------------------------------------------
 *
 * ---          HF - Application Development                       ---
 *              Copyright (c) 2013, ... All Rights Reserved
 *
 *
 *  Project     : domain
 *
 *  File        : Instrument.java
 *
 *  Author(s)   : hf
 *
 *  Created     : 16.12.2013
 *
 * ----------------------------------------------------------------------------
 */
 package de.hf.myfinance.instruments.persistence;
// Generated by Hibernate Tools 5.2.5.Final


import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Instrument generated by hbm2java
*/
@Entity
@Table(name="mf_instrument", indexes = { @Index(name = "instrument_unique_idx", unique = true, columnList = "businesskey")} )
@Inheritance(strategy= InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="instrumenttypeid", discriminatorType = DiscriminatorType.INTEGER)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public abstract class Instrument  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


    private Integer instrumentid;
    private Integer instrumentTypeId;
    private InstrumentType instrumentType;
    private String description;
    private boolean isactive;
    private LocalDate maturitydate;
    private LocalDate closingdate;
    private LocalDateTime treelastchanged;
    private String businesskey;

    protected Instrument() {
    }

    protected Instrument(InstrumentType instrumentType, String description, boolean isactive, LocalDateTime treelastchanged) {
        setInstrumentTypeId(instrumentType.getValue());
        this.description = description;
        this.isactive = isactive;
        this.treelastchanged = treelastchanged;
    }

    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="instrumentid", unique=true, nullable=false)
    public Integer getInstrumentid() {
        return this.instrumentid;
    }
    public void setInstrumentid(Integer instrumentid) {
        this.instrumentid = instrumentid;
    }

    @Column(name = "instrumenttypeid", nullable=false, insertable=false, updatable=false)
    protected Integer getInstrumentTypeId() {
        return this.instrumentTypeId;
    }
    protected void setInstrumentTypeId(Integer instrumentTypeId) {
        this.instrumentTypeId = instrumentTypeId;
        instrumentType = InstrumentType.getInstrumentTypeById(instrumentTypeId);
    }
    @Transient
    public InstrumentType getInstrumentType(){
        return instrumentType;
    }

    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="isactive", nullable=false)
    public boolean isIsactive() {
        return this.isactive;
    }
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }
    
    @Column(name="maturitydate", length=13)
    public LocalDate getMaturitydate() {
        return this.maturitydate;
    }
    public void setMaturitydate(LocalDate maturitydate) {
        this.maturitydate = maturitydate;
    }
    
    @Column(name="closingdate", length=13)
    public LocalDate getClosingdate() {
        return this.closingdate;
    }
    public void setClosingdate(LocalDate closingdate) {
        this.closingdate = closingdate;
    }
    
    @Column(name="treelastchanged", nullable=false, length=13)
    public LocalDateTime getTreelastchanged() {
        return this.treelastchanged;
    }
    public void setTreelastchanged(LocalDateTime treelastchanged) {
        this.treelastchanged = treelastchanged;
    }

    @Column(name="businesskey", length=32)
    public String getBusinesskey() {
        return this.businesskey;
    }
    public void setBusinesskey(String businesskey) {
        this.businesskey = businesskey;
    }

}
